name: film_uygulamasi
description: A new Flutter project.

version: 1.0.0+1

environment:
  sdk: '>=2.19.5 <3.0.0'


dependencies:
  flutter:
    sdk: flutter




  chewie: ^1.4.0
  google_fonts: ^4.0.3
  animated_bottom_navigation_bar: ^1.2.0
  path_provider: ^2.0.14
  http: ^0.13.6
  open_file_plus: ^3.4.1
  sqflite: ^2.2.8+2
  firebase_core:
  firebase_auth:
  cloud_firestore:
  firebase_storage:
  firebase_messaging:
  firebase_analytics:
  charts_flutter: ^0.12.0
  translator: ^0.1.7

dev_dependencies:
  flutter_test:
    sdk: flutter


  flutter_lints: ^2.0.0


flutter:


  uses-material-design: true


  assets:
  - assets/resimler/yenifilmler/
  - assets/resimler/gelecekfilmler/
  - assets/resimler/populerfilmler/
  - assets/videolar/



