// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
      apiKey: "AIzaSyBnExBhkH_pWuXFXr-wkvbRMZTxYa0tWds",
      authDomain: "movieappfirebase-f4baf.firebaseapp.com",
      projectId: "movieappfirebase-f4baf",
      storageBucket: "movieappfirebase-f4baf.appspot.com",
      messagingSenderId: "157401583203",
      appId: "1:157401583203:web:8f732622af9aff02f7f256",
      measurementId: "G-5H045PK8N1"
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBOdZOdKxFLY1n4Ti7pjE6aWv2n__QxEwc',
    appId: '1:157401583203:android:1a7a8b19a3990c26f7f256',
    messagingSenderId: '157401583203',
    projectId: 'movieappfirebase-f4baf',
    storageBucket: 'movieappfirebase-f4baf.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCF4ctv7WVXz00lSqXWo-gMMu5pnBb5sxU',
    appId: '1:157401583203:ios:0bedb95795d3ad2ef7f256',
    messagingSenderId: '157401583203',
    projectId: 'movieappfirebase-f4baf',
    storageBucket: 'movieappfirebase-f4baf.appspot.com',
    iosClientId: '157401583203-rla39c882673n4b3cgqjl80bke62qebk.apps.googleusercontent.com',
    iosBundleId: 'com.example.filmUygulamasi',
  );
}
